// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Copyright: typeof import('./src/components/plugins/copyright/index.vue')['default']
    Editor: typeof import('./src/components/plugins/editor/index.vue')['default']
    Group: typeof import('./src/components/media/group.vue')['default']
    GroupCreate: typeof import('./src/components/media/group-create.vue')['default']
    Icon: typeof import('./src/components/select-modal/icon/index.vue')['default']
    Layout: typeof import('./src/components/layouts/Layout.vue')['default']
    LayoutBody: typeof import('./src/components/layouts/LayoutBody.vue')['default']
    LayoutBodyTabs: typeof import('./src/components/layouts/LayoutBodyTabs.vue')['default']
    LayoutNav: typeof import('./src/components/layouts/LayoutNav.vue')['default']
    LayoutSideMenu: typeof import('./src/components/layouts/LayoutSideMenu.vue')['default']
    LayoutSideMenuChilden: typeof import('./src/components/layouts/LayoutSideMenuChilden.vue')['default']
    List: typeof import('./src/components/media/list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./src/components/select-modal/rule/index.vue')['default']
    SearchMap: typeof import('./src/components/plugins/search-map/index.vue')['default']
    SelectModal: typeof import('./src/components/media/select-modal.vue')['default']
    ShortcutsTime: typeof import('./src/components/plugins/shortcuts-time/index.vue')['default']
    UpdateName: typeof import('./src/components/media/update-name.vue')['default']
    UpdatePassword: typeof import('./src/components/system/admin/update-password.vue')['default']
    Upload: typeof import('./src/components/media/upload.vue')['default']
    UploadBtn: typeof import('./src/components/plugins/upload-btn/index.vue')['default']
    VideoPlay: typeof import('./src/components/plugins/video-play/index.vue')['default']
  }
}
